---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about-company.html $DEPLOYPATH
    - /bin/cp contact-company.html $DEPLOYPATH
    - /bin/cp project-company.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH